version: '3.9'
services:
  api:
    build: .
    ports: ['3000:3000']
    env_file: .env
    volumes: ['.:/app']
    depends_on: [db]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: